-- Run in Supabase SQL Editor to replace filler data/schema with your shop.db schema.

drop table if exists shipments cascade;
drop table if exists product_reviews cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists products cascade;
drop table if exists customers cascade;

create table customers (
  customer_id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  gender text not null,
  birthdate text not null,
  created_at text not null,
  city text,
  state text,
  zip_code text,
  customer_segment text,
  loyalty_tier text,
  is_active integer not null default 1 check (is_active in (0, 1))
);

create table products (
  product_id bigint generated by default as identity primary key,
  sku text not null unique,
  product_name text not null,
  category text not null,
  price numeric(12, 2) not null,
  cost numeric(12, 2) not null,
  is_active integer not null default 1 check (is_active in (0, 1))
);

create table orders (
  order_id bigint generated by default as identity primary key,
  customer_id bigint not null references customers(customer_id),
  order_datetime text not null,
  billing_zip text,
  shipping_zip text,
  shipping_state text,
  payment_method text not null,
  device_type text not null,
  ip_country text not null,
  promo_used integer not null default 0 check (promo_used in (0, 1)),
  promo_code text,
  order_subtotal numeric(12, 2) not null,
  shipping_fee numeric(12, 2) not null,
  tax_amount numeric(12, 2) not null,
  order_total numeric(12, 2) not null,
  risk_score numeric(8, 3) not null,
  is_fraud integer not null default 0 check (is_fraud in (0, 1))
);

create table order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references orders(order_id),
  product_id bigint not null references products(product_id),
  quantity integer not null,
  unit_price numeric(12, 2) not null,
  line_total numeric(12, 2) not null
);

create table product_reviews (
  review_id bigint generated by default as identity primary key,
  customer_id bigint not null references customers(customer_id),
  product_id bigint not null references products(product_id),
  rating integer not null check (rating between 1 and 5),
  review_datetime text not null,
  review_text text,
  unique(customer_id, product_id)
);

create table shipments (
  shipment_id bigint generated by default as identity primary key,
  order_id bigint not null unique references orders(order_id),
  ship_datetime text not null,
  carrier text not null,
  shipping_method text not null,
  distance_band text not null,
  promised_days integer not null,
  actual_days integer not null,
  late_delivery integer not null default 0 check (late_delivery in (0, 1))
);

create index idx_orders_customer_id on orders(customer_id);
create index idx_order_items_order_id on order_items(order_id);
create index idx_order_items_product_id on order_items(product_id);
create index idx_reviews_customer_id on product_reviews(customer_id);
create index idx_reviews_product_id on product_reviews(product_id);
